version: '3.8'
services:
  watchflix:
    build: 
      context: .
    volumes:
      - .:/watchflix
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start
    stdin_open: true